spring.datasource.url=jdbc:mysql://localhost:3306/mm_db
spring.datasource.username=root
spring.datasource.password=vinu
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=PartyMember
item.discount.price=400
spring.security.user.name=root
spring.security.user.password=vinu1

##Second DATASOURCE PROPERTIES
#spring.datasource.second.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.second.url = jdbc:mysql://localhost:3306/mm_db2
#spring.datasource.second.username = root
#spring.datasource.second.password = vinu


# --- DEFAULT RATE LIMIT ---
myalerts.ratelimit.default.capacity=30
myalerts.ratelimit.default.period=60

# --- PER-DC OVERRIDES ---
myalerts.ratelimit.dcs.DC123.capacity=100
myalerts.ratelimit.dcs.DC123.period=60

myalerts.ratelimit.dcs.DC999.capacity=20
myalerts.ratelimit.dcs.DC999.period=30

myalerts.ratelimit.dcs.WH1.capacity=200
myalerts.ratelimit.dcs.WH1.period=60



GOOGLE_APPLICATION_CREDENTIALS=src/main/resources/service-account.json
# Path to the service account key file
spring.cloud.gcp.credentials.location=classpath:service-account.json

# Optional: specify the project ID
#spring.cloud.gcp.project-id=bigqueryproject-425617

spring.data.mongodb.uri=mongodb://localhost:27017/MMDb


server.port=9292


