spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: vinu
    url: jdbc:mysql://localhost:3306/his_db
  security:
    user:
      name: vinu
      password: secret
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432