spring.datasource.url=jdbc:mysql://localhost:3306/mm_db
spring.datasource.username=root
spring.datasource.password=vinu
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=PartyMember
item.discount.price=400
spring.security.user.name=root
spring.security.user.password=vinu1
##Second DATASOURCE PROPERTIES
#spring.datasource.second.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.second.url = jdbc:mysql://localhost:3306/mm_db2
#spring.datasource.second.username = root
#spring.datasource.second.password = vinu
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# --- DEFAULT RATE LIMIT ---
myalerts.ratelimit.default.capacity=30
myalerts.ratelimit.default.period=60
# --- PER-DC OVERRIDES ---
myalerts.ratelimit.dcs.DC123.capacity=100
myalerts.ratelimit.dcs.DC123.period=60
myalerts.ratelimit.dcs.DC999.capacity=20
myalerts.ratelimit.dcs.DC999.period=30
myalerts.ratelimit.dcs.WH1.capacity=200
myalerts.ratelimit.dcs.WH1.period=60
GOOGLE_APPLICATION_CREDENTIALS=src/main/resources/service-account.json
# Path to the service account key file
spring.cloud.gcp.credentials.location=classpath:service-account.json
# Optional: specify the project ID
#spring.cloud.gcp.project-id=bigqueryproject-425617
spring.data.mongodb.uri=mongodb://localhost:27017/MMDb
server.port=9292
# Circuit Breaker Configuration for Kafka
resilience4j.circuitbreaker.instances.kafkaPublisher.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.kafkaPublisher.sliding-window-size=10
resilience4j.circuitbreaker.instances.kafkaPublisher.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.kafkaPublisher.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafkaPublisher.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.kafkaPublisher.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.instances.kafkaPublisher.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.kafkaPublisher.register-health-indicator=true
# Alert Recovery Scheduler Configuration
alert.recovery.batch-size=100
alert.recovery.max-attempts=5
alert.recovery.min-age-seconds=6
alert.recovery.throttle-ms=100

# --- ACTUATOR HEALTH CHECKS ---
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoint.health.probes.enabled=true


# Add to application.properties ? restart app ? done!
lab.thresholds.URIC_ACID.critical-low=2.0
lab.thresholds.URIC_ACID.urgent-low=3.0
lab.thresholds.URIC_ACID.urgent-high=7.0
lab.thresholds.URIC_ACID.critical-high=12.0
lab.thresholds.URIC_ACID.unit=mg/dL
lab.thresholds.URIC_ACID.description=Uric Acid